config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :merchants do
    collection do
      get :deleteall
      get :priceasc
      get :pricedesc
      get :scoreasc
      get :scoredesc
    end
  end
  resources :users
  resources :citys do
    member do
      get :collect
    end
    collection do
      get :collectcity
      get :deleteall
    end
  end
  resources :daijinjuans do
    collection do
      get :originpriceasc
      get :originpricedesc
      get :priceasc
      get :pricedesc
      get :soldsasc
      get :soldsdesc
    end
  end
  resources :maidans
  resources :tuangous do
    collection do
      get :originpriceasc
      get :originpricedesc
      get :priceasc
      get :pricedesc
      get :soldsasc
      get :soldsdesc
    end
  end
  # sidekiq网页客服端
  mount Sidekiq::Web => '/admin/sidekiq'
  root to: "merchants#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/daijinjuan.rb
class Daijinjuan
  include Mongoid::Document
  include Mongoid::Timestamps
  # 代金券ID
  field :dealid, type: Integer
  # 图片地址
  field :imgurl, type: String
  # 原价格
  field :originprice, type: Integer
  # 现在价格
  field :price, type: Integer
  # 已售数量
  field :solds, type: Integer
  field :stid, type: String
  # 标题
  field :title, type: String
  # 关联关系
  belongs_to :merchant
end

app/controllers/daijinjuans_controller.rb
class DaijinjuansController < ApplicationController
  before_action :authenticate_user!
  before_action :set_daijinjuan, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  def index
    @daijinjuans = Daijinjuan.all.page params[:page]
    # 搜索
    @daijinjuans = @daijinjuans.where(merchant_id: params[:merchant_id]) unless params[:merchant_id].blank?
    @daijinjuans = @daijinjuans.page params[:page]
  end

  def show
  end
  # 根据原价格升序排序
  def originpriceasc
    @daijinjuans = Daijinjuan.all.page params[:page]
    @daijinjuans = @daijinjuans.order_by(:originprice.asc)
    render :index
  end
  # 根据原价格降序排序
  def originpricedesc
    @daijinjuans = Daijinjuan.all.page params[:page]
    @daijinjuans = @daijinjuans.order_by(:originprice.desc)
    render :index
  end
  # 根据现价格升序排序
  def priceasc
    @daijinjuans = Daijinjuan.all.page params[:page]
    @daijinjuans = @daijinjuans.order_by(:price.asc)
    render :index
  end
  # 根据现价格降序排序
  def pricedesc
    @daijinjuans = Daijinjuan.all.page params[:page]
    @daijinjuans = @daijinjuans.order_by(:price.desc)
    render :index
  end
  # 根据售出数量升序排序
  def soldsasc
    @daijinjuans = Daijinjuan.all.page params[:page]
    @daijinjuans = @daijinjuans.order_by(:solds.asc)
    render :index
  end
  # 根据售出数量降序排序
  def soldsdesc
    @daijinjuans = Daijinjuan.all.page params[:page]
    @daijinjuans = @daijinjuans.order_by(:solds.desc)
    render :index
  end

  def new
    @daijinjuan = Daijinjuan.new
  end

  def edit
  end

  def create
    @daijinjuan = Daijinjuan.new(daijinjuan_params)

    respond_to do |format|
      if @daijinjuan.save
        format.html { redirect_to @daijinjuan, notice: 'Daijinjuan was successfully created.' }
        format.json { render :show, status: :created, location: @daijinjuan }
      else
        format.html { render :new }
        format.json { render json: @daijinjuan.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @daijinjuan.update(daijinjuan_params)
        format.html { redirect_to @daijinjuan, notice: 'Daijinjuan was successfully updated.' }
        format.json { render :show, status: :ok, location: @daijinjuan }
      else
        format.html { render :edit }
        format.json { render json: @daijinjuan.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @daijinjuan.destroy
    respond_to do |format|
      format.html { redirect_to daijinjuans_url, notice: 'Daijinjuan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_daijinjuan
      @daijinjuan = Daijinjuan.find(params[:id])
    end

    def daijinjuan_params
      params.require(:daijinjuan).permit(:dealid, :imgurl, :originprice, :price, :solds, :stid, :title)
    end
end

app/helpers/daijinjuans_helper.rb
module DaijinjuansHelper
end

app/views/daijinjuans/_form.html.erb
<%= simple_form_for(@daijinjuan, html: { multipart: true, class: "form-horizontal" }) do |f| %>
    <%= f.input :dealid, label: "代金券ID" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :imgurl, label: "图片地址" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :originprice, label: "原价格" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :price, label: "现在价格" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :solds, label: "已售数量" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :stid, label: "stid" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :title, label: "标题" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
  <div class="col-sm-10 col-sm-offset-2">
    <%= f.button :submit, "提 交", class: "btn btn-primary" %>
    <%= link_to "返 回", daijinjuans_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/daijinjuans/edit.html.erb
<div class="panel panel-default">
<div class="panel-heading font-bold">
  编辑代金券
</div>
<div class="panel-body">
<%= render 'form', daijinjuan: @daijinjuan %>
</div>
</div>

app/views/daijinjuans/index.html.erb
<div class="panel panel-default">
  <form action="/daijinjuans" method="get">
    商家ID
    <input type="text" id='merchant_id' name="merchant_id" value="<%= params[:merchant_id]%>">
    <input type="submit" name="" value="搜索">
  </form>
  <div class="panel-heading">
      代金券列表
  </div>
  <div class="table-responsive">
    <table class="table table-striped b-t b-light">
      <thead>
        <tr>
          <th>商家ID</th>
          <th>代金券ID</th>
          <th>原价格
            <a href="/daijinjuans/originpriceasc">
              <span class="glyphicon glyphicon-arrow-up" aria-hidden="true">
            </a>
            <a href="/daijinjuans/originpricedesc">
              <span class="glyphicon glyphicon-arrow-down" aria-hidden="true">
            </a>
          </th>
          <th>现在价格
            <a href="/daijinjuans/priceasc">
              <span class="glyphicon glyphicon-arrow-up" aria-hidden="true">
            </a>
            <a href="/daijinjuans/pricedesc">
              <span class="glyphicon glyphicon-arrow-down" aria-hidden="true">
            </a>
          </th>
          <th>已售数量
            <a href="/daijinjuans/soldsasc">
              <span class="glyphicon glyphicon-arrow-up" aria-hidden="true">
            </a>
            <a href="/daijinjuans/soldsdesc">
              <span class="glyphicon glyphicon-arrow-down" aria-hidden="true">
            </a>
          </th>
          <th>标题</th>
          <th style="width:120px;">创建时间</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
       <% @daijinjuans.each do |daijinjuan| %>
      <tr>
        <td><%= daijinjuan.merchant_id %></td>
        <td><%= daijinjuan.dealid %></td>
        <td><%= daijinjuan.originprice %></td>
        <td><%= daijinjuan.price %></td>
        <td><%= daijinjuan.solds %></td>
        <td><%= daijinjuan.title %></td>
        <td><%= daijinjuan.created_at.strftime("%F %T") %></td>
        <td><%= link_to '查看', daijinjuan, class: "btn btn-default btn-xs" %>
        <%= link_to '修改', edit_daijinjuan_path(daijinjuan), class: "btn btn-default btn-xs" %>
        <%= link_to '删除', daijinjuan_path(daijinjuan), method: :delete, class: "btn btn-default btn-xs"  %>
        </td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <footer class="panel-footer">
    <%= render partial: "shared/admin/paginate", locals: { object: @daijinjuans } %>
  </footer>
</div>

app/views/daijinjuans/new.html.erb
<div class="panel panel-default">
<div class="panel-heading font-bold">
  新建代金券
</div>
<div class="panel-body">
<%= render 'form', daijinjuan: @daijinjuan %>
</div>
</div>

app/views/daijinjuans/show.html.erb
<div class="panel panel-default">
<div class="panel-heading font-bold">
  查看代金券
</div>
<div class="panel-body">
  <%= simple_form_for(@daijinjuan, html: { multipart: true, class: "form-horizontal" }) do |f| %>
    <%= f.input :dealid, label: "代金券ID", disabled: true %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :imgurl, label: "图片地址", disabled: true %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :originprice, label: "原价格", disabled: true %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :price, label: "现在价格", disabled: true %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :solds, label: "已售数量", disabled: true %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :stid, label: "stid", disabled: true %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :title, label: "标题", disabled: true %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
  <div class="col-sm-10 col-sm-offset-2">
    <%= link_to "返 回", daijinjuans_path, class: "btn btn-default" %>
  </div>
  <% end %>
</div>
</div>