config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :merchants do
    collection do
      get :deleteall
      get :priceasc
      get :pricedesc
      get :scoreasc
      get :scoredesc
    end
  end
  resources :users
  resources :citys do
    member do
      get :collect
    end
    collection do
      get :collectcity
      get :deleteall
    end
  end
  resources :daijinjuans do
    collection do
      get :originpriceasc
      get :originpricedesc
      get :priceasc
      get :pricedesc
      get :soldsasc
      get :soldsdesc
    end
  end
  resources :maidans
  resources :tuangous do
    collection do
      get :originpriceasc
      get :originpricedesc
      get :priceasc
      get :pricedesc
      get :soldsasc
      get :soldsdesc
    end
  end
  # sidekiq网页客服端
  mount Sidekiq::Web => '/admin/sidekiq'
  root to: "merchants#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/merchant.rb
class Merchant
  include Mongoid::Document
  include Mongoid::Timestamps
  # 区域名
  field :areaname, type: String
  # 平均价格
  field :avgprice, type: Integer
  # 平均评分
  field :avgscore, type: Integer
  # 分类名
  field :catename, type: String
  # 分类标签
  field :channel, type: String
  # 城市POI ID
  field :ctpoi, type: String
  # 封面图片
  field :frontimg, type: String
  # 纬度
  field :lat, type: Float
  # 经度
  field :lng, type: Float
  # 商家名称
  field :name, type: String
  # POI ID
  field :poiid, type: Integer
  # 商家地址
  field :address, type: String
  # 商家电话
  field :phone, type: String
  # 关联关系
  belongs_to :city
  has_many :maidans, dependent: :delete # 级联删除
  has_many :daijinjuans, dependent: :delete
  has_many :tuangous, dependent: :delete
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  def index
    @merchants = Merchant.all.page params[:page]
    # 模糊搜索
    @merchants = @merchants.where(city_id: City.find_by(name: /#{params[:cityname]}/).id) unless params[:cityname].blank?
    @merchants = @merchants.where(name: /#{params[:name]}/) unless params[:name].blank?
    @merchants = @merchants.where(id: params[:id]) unless params[:id].blank?
    @merchants = @merchants.page params[:page]
  end

  def show
    @maidans = @merchant.maidans
    @daijinjuans = @merchant.daijinjuans
    @tuangous = @merchant.tuangous
  end
  # 删除所有商家信息
  def deleteall
    Merchant.destroy_all
    redirect_to merchants_path, notice: '数据已经删除!!!'
  end
  # 根据平均价格进行升序排序
  def priceasc
    @merchants = Merchant.all.page params[:page]
    @merchants = @merchants.order_by(:avgprice.asc)
    render :index
  end
  # 根据平均价格进行降序排序
  def pricedesc
    @merchants = Merchant.all.page params[:page]
    @merchants = @merchants.order_by(:avgprice.desc)
    render :index
  end
  # 根据平均评分进行升序排序
  def scoreasc
    @merchants = Merchant.all.page params[:page]
    @merchants = @merchants.order_by(:avgscore.asc)
    render :index
  end
  # 根据平均评分进行降序排序
  def scoredesc
    @merchants = Merchant.all.page params[:page]
    @merchants = @merchants.order_by(:avgscore.desc)
    render :index
  end

  def new
    @merchant = Merchant.new#current_user.merchants.build
  end

  def edit
  end

  def create
    @merchant = Merchant.new(merchant_params)

    respond_to do |format|
      if @merchant.save
        format.html { redirect_to @merchant, notice: 'Merchant was successfully created.' }
        format.json { render :show, status: :created, location: @merchant }
      else
        format.html { render :new }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @merchant.update(merchant_params)
        format.html { redirect_to @merchant, notice: 'Merchant was successfully updated.' }
        format.json { render :show, status: :ok, location: @merchant }
      else
        format.html { render :edit }
        format.json { render json: @merchant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @merchant.destroy
    respond_to do |format|
      format.html { redirect_to merchants_url, notice: 'Merchant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    def merchant_params
      params.require(:merchant).permit(:areaname, :avgprice, :avgscore, :catename, :channel, :ctpoi, :frontimg, :lat, :lng, :name, :poiid, :address, :phone)
    end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.erb
<%= simple_form_for(@merchant, html: { multipart: true, class: "form-horizontal" }) do |f| %>
    <%= f.input :areaname, label: "地区名" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :avgprice, label: "平均价格" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :avgscore, label: "平均评分" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :catename, label: "分类名" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :channel, label: "channel" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :ctpoi, label: "ctpoi" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :frontimg, label: "frontimg" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :lat, label: "lat" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :lng, label: "lng" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :name, label: "店铺名称" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :poiid, label: "poiid" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :address, label: "地址" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :phone, label: "电话" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
  <div class="col-sm-10 col-sm-offset-2">
    <%= f.button :submit, "提 交", class: "btn btn-primary" %>
    <%= link_to "返 回", merchants_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/merchants/edit.html.erb
<div class="panel panel-default">
<div class="panel-heading font-bold">
  编辑商家
</div>
<div class="panel-body">
<%= render 'form', merchant: @merchant %>
</div>
</div>

app/views/merchants/index.html.erb
<div class="panel panel-default">
  <form action="/merchants" method="get">
    城市名
    <input type="text" id='cityname' name="cityname" value="<%= params[:cityname]%>">
    店铺名称
    <input type="text" id='name' name="name" value="<%= params[:name]%>">
    商家ID
    <input type="text" id='id' name="id" value="<%= params[:id]%>">
    <input type="submit" name="" value="搜索">
  </form>
  <div class="panel-heading">
      商家列表
    <div class="pull-right">
      <%= link_to "一键删除", deleteall_merchants_path, class: "btn btn-primary btn-xs btn-danger" %>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table table-striped b-t b-light">
      <thead>
        <tr>
          <th>ID</th>
          <th>城市名</th>
          <th>地区名</th>
          <th>平均价格
            <a href="/merchants/priceasc">
              <span class="glyphicon glyphicon-arrow-up" aria-hidden="true">
            </a>
            <a href="/merchants/pricedesc">
              <span class="glyphicon glyphicon-arrow-down" aria-hidden="true">
            </a>
          </th>
          <th>平均评分
            <a href="/merchants/scoreasc">
              <span class="glyphicon glyphicon-arrow-up" aria-hidden="true">
            </a>
            <a href="/merchants/scoredesc">
              <span class="glyphicon glyphicon-arrow-down" aria-hidden="true">
            </a>
          </th>
          <th>分类名</th>
          <th>店铺名称</th>
          <th>地址</th>
          <th>电话</th>
          <th style="width:120px;">创建时间</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
       <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.id %></td>
        <td><%= merchant.city.name %></td>
        <td><%= merchant.areaname %></td>
        <td><%= merchant.avgprice %></td>
        <td><%= merchant.avgscore %></td>
        <td><%= merchant.catename %></td>
        <td><%= merchant.name %></td>
        <td><%= merchant.address %></td>
        <td><%= merchant.phone %></td>
        <td><%= merchant.created_at.strftime("%F %T") %></td>
        <td><%= link_to '查看', merchant, class: "btn btn-default btn-xs" %>
        <%= link_to '修改', edit_merchant_path(merchant), class: "btn btn-default btn-xs" %>
        <%= link_to '删除', merchant_path(merchant), method: :delete, class: "btn btn-default btn-xs"  %>
        </td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <footer class="panel-footer">
    <%= render partial: "shared/admin/paginate", locals: { object: @merchants } %>
  </footer>
</div>

app/views/merchants/new.html.erb
<div class="panel panel-default">
<div class="panel-heading font-bold">
  新建标签
</div>
<div class="panel-body">
<%= render 'form', merchant: @merchant %>
</div>
</div>

app/views/merchants/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading font-bold">
    查看商家
  </div>
  <div class="panel-body">
    <%= simple_form_for(@merchant, html: { multipart: true, class: "form-horizontal" }) do |f| %>
      <%= f.input :areaname, label: "地区名", disabled: true %>
    <div class="line line-dashed b-b line-lg pull-in"></div>
      <%= f.input :avgprice, label: "平均价格", disabled: true %>
    <div class="line line-dashed b-b line-lg pull-in"></div>
      <%= f.input :avgscore, label: "平均评分", disabled: true %>
    <div class="line line-dashed b-b line-lg pull-in"></div>
      <%= f.input :catename, label: "分类名", disabled: true %>
    <div class="line line-dashed b-b line-lg pull-in"></div>
      <%= f.input :channel, label: "channel", disabled: true %>
    <div class="line line-dashed b-b line-lg pull-in"></div>
      <%= f.input :ctpoi, label: "ctpoi", disabled: true %>
    <div class="line line-dashed b-b line-lg pull-in"></div>
      <%= f.input :frontimg, label: "frontimg", disabled: true %>
    <div class="line line-dashed b-b line-lg pull-in"></div>
      <%= f.input :lat, label: "lat", disabled: true %>
    <div class="line line-dashed b-b line-lg pull-in"></div>
      <%= f.input :lng, label: "lng", disabled: true %>
    <div class="line line-dashed b-b line-lg pull-in"></div>
      <%= f.input :name, label: "店铺名称", disabled: true %>
    <div class="line line-dashed b-b line-lg pull-in"></div>
      <%= f.input :poiid, label: "poiid", disabled: true %>
    <div class="line line-dashed b-b line-lg pull-in"></div>
      <%= f.input :address, label: "地址", disabled: true %>
    <div class="line line-dashed b-b line-lg pull-in"></div>
      <%= f.input :phone, label: "电话", disabled: true %>
    <div class="line line-dashed b-b line-lg pull-in"></div>
    <div class="col-sm-10 col-sm-offset-2"></div>
    <% end %>
  </div>
  <% if not @maidans.blank? %>
   <% index = 0 %>
    <% @maidans.each do |maidan| %>
      <div class="panel-heading font-bold">
        买单列表 <%= index = index + 1 %>
      </div>
      <div class="panel-body">
          <%= simple_form_for(maidan, html: { multipart: true, class: "form-horizontal" }) do |f| %>
            <%= f.input :content, label: "买单内容", disabled: true %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
          <div class="col-sm-10 col-sm-offset-2"></div>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <% if not @daijinjuans.blank? %>
    <% index = 0 %>
    <% @daijinjuans.each do |daijinjuan| %>
      <div class="panel-heading font-bold">
      代金券列表 <%= index = index + 1 %>
      </div>
      <div class="panel-body">
          <%= simple_form_for(daijinjuan, html: { multipart: true, class: "form-horizontal" }) do |f| %>
            <%= f.input :dealid, label: "代金券ID", disabled: true %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
            <%= f.input :imgurl, label: "图片地址", disabled: true %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
            <%= f.input :originprice, label: "原价格", disabled: true %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
            <%= f.input :price, label: "现在价格", disabled: true %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
            <%= f.input :solds, label: "已售数量", disabled: true %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
            <%= f.input :stid, label: "stid", disabled: true %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
            <%= f.input :title, label: "标题", disabled: true %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
          <div class="col-sm-10 col-sm-offset-2"></div>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <% if not @tuangous.blank? %>
    <% index = 0 %>
    <% @tuangous.each do |tuangou| %>
      <div class="panel-heading font-bold">
      团购列表 <%= index = index + 1 %>
      </div>
      <div class="panel-body">
          <%= simple_form_for(tuangou, html: { multipart: true, class: "form-horizontal" }) do |f| %>
            <%= f.input :dealid, label: "团购ID", disabled: true %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
            <%= f.input :imgurl, label: "图片地址", disabled: true %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
            <%= f.input :originprice, label: "原价格", disabled: true %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
            <%= f.input :price, label: "现在价格", disabled: true %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
            <%= f.input :solds, label: "已售数量", disabled: true %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
            <%= f.input :stid, label: "stid", disabled: true %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
            <%= f.input :title, label: "标题", disabled: true %>
          <div class="line line-dashed b-b line-lg pull-in"></div>
          <div class="col-sm-10 col-sm-offset-2"></div>
          <% end %>
      </div>
    <% end %>
  <% end %>
  <div class="panel-body">
    <div class="col-sm-10 col-sm-offset-2">
      <%= link_to "返 回", merchants_path, class: "btn btn-default" %>
    </div>
  </div>
</div>