config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :merchants do
    collection do
      get :deleteall
      get :priceasc
      get :pricedesc
      get :scoreasc
      get :scoredesc
    end
  end
  resources :users
  resources :citys do
    member do
      get :collect
    end
    collection do
      get :collectcity
      get :deleteall
    end
  end
  resources :daijinjuans do
    collection do
      get :originpriceasc
      get :originpricedesc
      get :priceasc
      get :pricedesc
      get :soldsasc
      get :soldsdesc
    end
  end
  resources :maidans
  resources :tuangous do
    collection do
      get :originpriceasc
      get :originpricedesc
      get :priceasc
      get :pricedesc
      get :soldsasc
      get :soldsdesc
    end
  end
  # sidekiq网页客服端
  mount Sidekiq::Web => '/admin/sidekiq'
  root to: "merchants#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/city.rb
class City
  include Mongoid::Document
  include Mongoid::Timestamps
  # 城市id
  field :ci, type: Integer
  # 城市名
  field :name, type: String
  # 城市拼音
  field :citypinyin, type: String
  #关联关系
  has_many :merchants, dependent: :delete # 级联删除
end

app/controllers/citys_controller.rb
class CitysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_city, only: [:show, :edit, :update, :destroy, :collect]
  layout 'admin'

  def index
    @citys = City.all.page params[:page]
    # 搜索
    @citys = @citys.where(name: params[:name]) unless params[:name].blank?
    @citys = @citys.page params[:page]
  end

  def show
  end
  # 根据城市ID进行采集数据
  def collect
    ci = City.find(params[:id]).ci
    MerchantWorker.perform_async(ci)
    redirect_to citys_path, notice: '数据采集正在进行..........'
  end
  # 采集城市信息
  def collectcity
    CityCollectWorker.perform_async()
    redirect_to citys_path, notice: '城市数据采集正在进行..........'
  end
  # 删除所有城市信息
  def deleteall
    City.destroy_all
    redirect_to citys_path, notice: '数据已经删除!!!'
  end

  def new
    @city = City.new
  end

  def edit
  end

  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to citys_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_city
      @city = City.find(params[:id])
    end

    def city_params
      params.require(:city).permit(:ci, :name, :citypinyin)
    end
end

app/helpers/citys_helper.rb
module CitysHelper
end

app/views/citys/_form.html.erb
<%= simple_form_for(@city, html: { multipart: true, class: "form-horizontal" }) do |f| %>
    <%= f.input :name, label: "城市名" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :ci, label: "城市ID" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :citypinyin, label: "城市拼音" %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
  <div class="col-sm-10 col-sm-offset-2">
    <%= f.button :submit, "提 交", class: "btn btn-primary" %>
    <%= link_to "返 回", citys_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/citys/edit.html.erb
<div class="panel panel-default">
<div class="panel-heading font-bold">
  编辑城市
</div>
<div class="panel-body">
<%= render 'form', city: @city %>
</div>
</div>

app/views/citys/index.html.erb
<div class="panel panel-default">
  <form action="/citys" method="get">
    城市名
    <input type="text" id='name' name="name" value="<%= params[:name]%>">
    <input type="submit" name="" value="搜索">
  </form>
  <div class="panel-heading">
      城市列表
    <div class="pull-right">
      <%= link_to "一键删除", deleteall_citys_path, class: "btn btn-primary btn-xs btn-danger" %>
    </div>
    <div class="pull-right">
      <%= link_to "采集城市", collectcity_citys_path, class: "btn btn-primary btn-xs" %>
       &nbsp; &nbsp;
    </div>
  </div>
  <div class="table-responsive">
    <table class="table table-striped b-t b-light">
      <thead>
        <tr>
          <th>城市名</th>
          <th>城市ID</th>
          <th>城市拼音</th>
          <th style="width:120px;">创建时间</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
       <% @citys.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= city.ci %></td>
        <td><%= city.citypinyin %></td>
        <td><%= city.created_at.strftime("%F %T") %></td>
        <td><%= link_to '查看', city, class: "btn btn-default btn-xs" %>
        <%= link_to '修改', edit_city_path(city), class: "btn btn-default btn-xs" %>
        <%= link_to '删除', city_path(city), method: :delete, class: "btn btn-default btn-xs"  %>
        <%= link_to '采集', collect_city_path(city.id), class: "btn btn-default btn-xs btn-danger"  %>
        </td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <footer class="panel-footer">
    <%= render partial: "shared/admin/paginate", locals: { object: @citys } %>
  </footer>
</div>

app/views/citys/new.html.erb
<div class="panel panel-default">
<div class="panel-heading font-bold">
  新建城市
</div>
<div class="panel-body">
<%= render 'form', city: @city %>
</div>
</div>

app/views/citys/show.html.erb
<div class="panel panel-default">
<div class="panel-heading font-bold">
  查看城市
</div>
<div class="panel-body">
  <%= simple_form_for(@city, html: { multipart: true, class: "form-horizontal" }) do |f| %>
    <%= f.input :name, label: "城市名", disabled: true %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :ci, label: "城市ID", disabled: true %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
    <%= f.input :citypinyin, label: "城市拼音", disabled: true %>
  <div class="line line-dashed b-b line-lg pull-in"></div>
  <div class="col-sm-10 col-sm-offset-2">
    <%= link_to "返 回", citys_path, class: "btn btn-default" %>
  </div>
  <% end %>
</div>
</div>